import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Heart, MapPin, Search, Utensils, Music2, Trees, Palette, Users, Star, Share2, ShoppingBag, Ticket, Footprints, Trophy } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

type CardItem={id:string;label:string;title:string;meta:string;category:string;tags:string[];free?:boolean;tone:string;imageUrl?:string|null;sourceUrl?:string|null;startTime?:string|null};
const supabase=createClient('https://vtvxzdvsnjhdkgtgzdxw.supabase.co','sb_publishable_aFbMLAqQB9NGtqcEL3xf4w_tj-o5M3p');
const TZ='America/Indiana/Indianapolis';
const categoryOptions=[{label:'LIVE MUSIC',value:'Music',icon:Music2},{label:'FAMILY FUN',value:'Family',icon:Users},{label:'EVENTS',value:'__events__',icon:Ticket},{label:'ARTS & CULTURE',value:'Arts',icon:Palette},{label:'OUTDOORS',value:'Outdoors',icon:Footprints},{label:'PARKS',value:'Parks',icon:Trees},{label:'SHOPPING',value:'Shopping',icon:ShoppingBag},{label:'FOOD & DRINK',value:'Food',icon:Utensils},{label:'ALL CATEGORIES',value:'All',icon:CalendarDays}];
const tone=(c:string)=>{const x=c.toLowerCase();return x.includes('music')?'music':x.includes('sport')?'sports':x.includes('food')?'food':x.includes('outdoor')||x.includes('park')?'outdoors':x.includes('family')?'family':x.includes('art')?'arts':'festival'};
const cardIcon=(c:string)=>{const x=c.toLowerCase();if(x.includes('music'))return Music2;if(x.includes('sport'))return Trophy;if(x.includes('food'))return Utensils;if(x.includes('outdoor')||x.includes('park'))return Trees;if(x.includes('family'))return Users;if(x.includes('art'))return Palette;if(x.includes('shop'))return ShoppingBag;return Ticket};
const eventMeta=(e:any)=>{const d=new Date(e.start_time);return `${d.toLocaleDateString('en-US',{timeZone:TZ,month:'short',day:'numeric'})} · ${d.toLocaleTimeString('en-US',{timeZone:TZ,hour:'numeric',minute:'2-digit'})}${e.venue_name?` · ${e.venue_name}`:''}`};
const localParts=(d:Date)=>{const p=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).formatToParts(d);const get=(t:string)=>p.find(x=>x.type===t)?.value||'';return{key:`${get('year')}-${get('month')}-${get('day')}`,weekday:get('weekday')}};
const isInScope=(iso:string|undefined|null,scope:string)=>{if(!iso)return true;const d=new Date(iso),now=new Date();if(scope==='TODAY')return localParts(d).key===localParts(now).key;if(scope==='THIS WEEK')return d>=now&&d<=new Date(now.getTime()+7*86400000);const dayMap:any={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};const days=(6-dayMap[localParts(now).weekday]+7)%7;const sat=new Date(now.getTime()+days*86400000);const sun=new Date(sat.getTime()+2*86400000);return d>=sat&&d<sun;};
const safeUrl=(url?:string|null)=>{if(!url)return null;try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}};

export default function App(){
 const[filter,setFilter]=useState<string|null>(null);const[scope,setScope]=useState('TODAY');const[saved,setSaved]=useState<string[]>([]);const[showSaved,setShowSaved]=useState(false);const[items,setItems]=useState<CardItem[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');
 useEffect(()=>{const raw=localStorage.getItem('imbored-saved');if(raw)try{setSaved(JSON.parse(raw))}catch{};(async()=>{setLoading(true);const now=new Date().toISOString();const[{data:events},{data:places}]=await Promise.all([supabase.from('events').select('id,title,category,tags,start_time,venue_name,is_free,image_url,source_url,family_friendly').eq('status','active').gte('start_time',now).order('start_time').limit(150),supabase.from('places').select('id,name,category,tags,city,image_url,website_url').eq('active',true).limit(150)]);const ev=(events||[]).map((e:any):CardItem=>({id:`e-${e.id}`,label:e.is_free?'FREE':'VERIFIED',title:e.title,meta:eventMeta(e),category:e.category||'Community',tags:[...(e.tags||[]),...(e.family_friendly?['Family']:[])],free:e.is_free,tone:tone(e.category||''),imageUrl:e.image_url,sourceUrl:safeUrl(e.source_url),startTime:e.start_time}));const placesMapped=(places||[]).map((p:any):CardItem=>{const tags=p.tags||[];const category=String(p.category||'').toLowerCase().includes('food')||tags.some((t:string)=>/food|restaurant|coffee|dessert/i.test(t))?'Food':String(p.category||'').toLowerCase().includes('shop')?'Shopping':String(p.category||'').toLowerCase().includes('park')?'Parks':p.category||'Place';return{id:`p-${p.id}`,label:'LOCAL',title:p.name,meta:`${p.city||'Michiana'} · Local place`,category,tags:[category,...tags.slice(0,2)],tone:tone(category),imageUrl:p.image_url,sourceUrl:safeUrl(p.website_url),startTime:null}});setItems([...ev,...placesMapped]);setLoading(false)})()},[]);
 useEffect(()=>{localStorage.setItem('imbored-saved',JSON.stringify(saved))},[saved]);
 const visible=useMemo(()=>items.filter(i=>{const q=query.trim().toLowerCase();if(showSaved&&!saved.includes(i.id))return false;if(q&&!`${i.title} ${i.category} ${i.meta} ${i.tags.join(' ')}`.toLowerCase().includes(q))return false;if(filter==='__events__'&&!i.id.startsWith('e-'))return false;if(filter&&filter!=='__events__'&&!(i.category===filter||i.tags.includes(filter)))return false;if(i.id.startsWith('e-')&&!isInScope(i.startTime,scope))return false;return true}),[items,filter,query,scope,showSaved,saved]);
 const toggle=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const chooseScope=(next:string)=>{setScope(next);setShowSaved(false);setFilter(null);requestAnimationFrame(()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth',block:'start'}))};
 const openItem=(url?:string|null)=>{const href=safeUrl(url);if(href)window.open(href,'_blank','noopener,noreferrer')};
 const ScopeButtons=()=> <>{['TODAY','THIS WEEK','WEEKEND'].map(s=><button key={s} className={scope===s&&!showSaved?'active':''} onClick={()=>chooseScope(s)}>{s}</button>)}</>;
 return <div className="site-shell">
  <header className="site-header"><button className="mini-brand" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="I'm Bored home"><span className="mini-logo-crop"><img src="/im-bored-logo.webp" alt="I'm Bored"/></span></button><nav className="top-nav"><ScopeButtons/><button onClick={()=>document.getElementById('categories')?.scrollIntoView({behavior:'smooth'})}>CATEGORIES</button></nav><div className="header-actions"><button className={showSaved?'active':''} onClick={()=>{setShowSaved(v=>!v);setTimeout(()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth'}),0)}}><Heart size={19} fill={showSaved?'currentColor':'none'}/> FAVORITES</button></div></header>
  <nav className="mobile-scope-nav" aria-label="Time filters"><ScopeButtons/></nav>
  <main>
   <section className="brand-hero"><div className="hero-overlay"><img className="hero-logo" src="/im-bored-logo.webp" alt="I'm Bored, Find Something Fun to Do"/><div className="location-row"><span>SOUTH BEND</span><b>•</b><span>MISHAWAKA</span><b>•</b><span>ELKHART</span><b>•</b><span>NILES</span></div><div className="search-bar"><Search size={24}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')document.getElementById('results')?.scrollIntoView({behavior:'smooth'})}} placeholder="Search events, concerts, festivals, activities..."/><span className="area-label"><MapPin size={18}/> Michiana · 30 mi</span><button className="search-button" onClick={()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth'})}>SEARCH</button></div></div></section>
   <section className="category-strip" id="categories">{categoryOptions.map(({label,value,icon:I})=>{const active=value==='All'?filter===null:filter===value;return <button key={label} className={active?'category active':'category'} onClick={()=>{setShowSaved(false);setFilter(value==='All'?null:value);requestAnimationFrame(()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth'}))}}><span className="category-icon"><I/></span><small>{label}</small></button>})}</section>
   <section className="content-wrap" id="results"><div className="section-title"><div><Star fill="currentColor"/><h2>{showSaved?'Saved':filter==='__events__'?'All':filter||(scope==='TODAY'?'Today':scope==='THIS WEEK'?'This Week':'Weekend')} Events</h2></div><span>{loading?'Loading…':`${visible.length} verified options`}</span></div><div className="featured-grid">{visible.slice(0,24).map(e=>{const Visual=cardIcon(e.category);return <article className={`featured-card ${e.sourceUrl?'clickable':''}`} key={e.id} onClick={()=>openItem(e.sourceUrl)}><div className={`card-photo ${e.tone} ${e.imageUrl?'has-image':'fallback'}`} style={e.imageUrl?{backgroundImage:`url(${e.imageUrl})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}>{!e.imageUrl&&<div className="fallback-art"><span className="fallback-orb"><Visual size={54}/></span><span className="fallback-label">{e.category}</span></div>}<span className="date-badge">{scope}</span><button className="favorite" onClick={ev=>{ev.stopPropagation();toggle(e.id)}} aria-label="Save"><Heart size={19} fill={saved.includes(e.id)?'currentColor':'none'}/></button></div><div className="card-copy"><p className="category-label">{e.category}</p><h3>{e.title}</h3><p className="card-meta"><MapPin size={15}/><span>{e.meta}</span></p>{!e.sourceUrl&&<span className="link-note">Details link unavailable</span>}</div></article>})}</div>{!loading&&!visible.length&&<p className="empty-state">No verified matches for this view yet. Try This Week or All Categories.</p>}</section>
   <section className="benefits"><div><MapPin/><strong>LOCAL FOCUS</strong><span>Events in South Bend, Mishawaka, Elkhart & Niles</span></div><div><CalendarDays/><strong>ALWAYS UPDATED</strong><span>Fresh listings from verified local sources</span></div><div><Heart/><strong>SAVE FAVORITES</strong><span>Save ideas and plan your perfect day</span></div><div><Share2/><strong>SHARE & EXPLORE</strong><span>Find something fun and bring someone along</span></div></section>
   <footer className="photo-credit">Hero photo: St. Joseph River at Leeper Park, South Bend, Tony Webster, CC BY 2.0.</footer>
  </main>
 </div>
}
