import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Heart, MapPin, Search, UserRound, Utensils, Music2, Trophy, Trees, Palette, Users, MoonStar, Star, Share2 } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

type CardItem={id:string;label:string;title:string;meta:string;category:string;tags:string[];free?:boolean;tone:string;imageUrl?:string|null;sourceUrl?:string|null};
const supabase=createClient('https://vtvxzdvsnjhdkgtgzdxw.supabase.co','sb_publishable_aFbMLAqQB9NGtqcEL3xf4w_tj-o5M3p');
const filters=['Family','Food','Music','Sports','Date Night','Arts','Outdoors'];
const icons:any={Family:Users,Food:Utensils,Music:Music2,Sports:Trophy,'Date Night':MoonStar,Arts:Palette,Outdoors:Trees};
const tone=(c:string)=>{const x=c.toLowerCase();return x.includes('music')?'music':x.includes('sport')?'sports':x.includes('food')?'food':x.includes('outdoor')?'outdoors':x.includes('family')?'family':x.includes('art')?'arts':'festival'};
const eventMeta=(e:any)=>{const d=new Date(e.start_time);return `${d.toLocaleDateString([], {month:'short',day:'numeric'})} · ${d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}${e.venue_name?` · ${e.venue_name}`:''}`};

export default function App(){
 const[filter,setFilter]=useState<string|null>(null);const[saved,setSaved]=useState<string[]>([]);const[items,setItems]=useState<CardItem[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');
 useEffect(()=>{(async()=>{setLoading(true);const now=new Date().toISOString();const[{data:events},{data:places}]=await Promise.all([supabase.from('events').select('id,title,category,tags,start_time,venue_name,is_free,image_url,source_url,family_friendly').eq('status','active').gte('start_time',now).order('start_time').limit(80),supabase.from('places').select('id,name,category,tags,city,image_url,website_url').eq('active',true).limit(80)]);const ev=(events||[]).map((e:any):CardItem=>({id:`e-${e.id}`,label:e.is_free?'Free Pick':'Verified',title:e.title,meta:eventMeta(e),category:e.category||'Community',tags:[...(e.tags||[]),...(e.family_friendly?['Family']:[])],free:e.is_free,tone:tone(e.category||''),imageUrl:e.image_url,sourceUrl:e.source_url}));const food=(places||[]).filter((p:any)=>String(p.category||'').toLowerCase().includes('food')||(p.tags||[]).some((t:string)=>/food|restaurant|coffee|dessert/i.test(t))).map((p:any):CardItem=>({id:`p-${p.id}`,label:'Local Food',title:p.name,meta:`${p.city||'Michiana'} · Local place`,category:'Food',tags:['Food',...(p.tags||[]).slice(0,1)],tone:'food',imageUrl:p.image_url,sourceUrl:p.website_url}));setItems([...ev,...food]);setLoading(false)})()},[]);
 const visible=useMemo(()=>items.filter(i=>{const q=query.trim().toLowerCase();if(q&&!`${i.title} ${i.category} ${i.meta} ${i.tags.join(' ')}`.toLowerCase().includes(q))return false;if(filter==='Date Night')return i.tags.includes('Date Night')||['Food','Music','Arts'].includes(i.category);if(filter&&!(i.category===filter||i.tags.includes(filter)))return false;return true}),[items,filter,query]);
 const toggle=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <div className="site-shell">
  <header className="site-header"><div className="mini-brand"><span className="mini-mark">IB</span><span>I’mBored</span></div><nav className="top-nav"><button className="active">TODAY</button><button>THIS WEEK</button><button>WEEKEND</button><button>CATEGORIES</button><button>AREAS</button><button>SUBMIT EVENT</button></nav><div className="header-actions"><button><Heart size={19}/> Favorites</button><button><UserRound size={19}/> Sign in</button></div></header>
  <main>
   <section className="brand-hero"><div className="hero-overlay"><img className="hero-logo" src="/im-bored-logo.webp" alt="I'm Bored, Find Something Fun to Do"/><div className="location-row"><span>SOUTH BEND</span><b>•</b><span>MISHAWAKA</span><b>•</b><span>ELKHART</span><b>•</b><span>NILES</span></div><div className="search-bar"><Search size={22}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search events, concerts, festivals, activities..."/><button className="area-button"><MapPin size={18}/> All Areas</button><button className="search-button">SEARCH</button></div></div></section>
   <section className="category-strip"><button className={!filter?'category active':''} onClick={()=>setFilter(null)}><span className="category-icon"><CalendarDays/></span><small>ALL</small></button>{filters.map(x=>{const I=icons[x];return <button key={x} className={filter===x?'category active':'category'} onClick={()=>setFilter(filter===x?null:x)}><span className="category-icon"><I/></span><small>{x.toUpperCase()}</small></button>})}</section>
   <section className="content-wrap"><div className="section-title"><div><Star fill="currentColor"/><h2>{filter?filter:'Featured'} Events</h2></div><span>{loading?'Loading…':`${visible.length} verified options`}</span></div><div className="featured-grid">{visible.slice(0,12).map((e,i)=><article className="featured-card" key={e.id} onClick={()=>e.sourceUrl&&window.open(e.sourceUrl,'_blank','noopener,noreferrer')}><div className={`card-photo ${e.tone}`} style={e.imageUrl?{backgroundImage:`url(${e.imageUrl})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><span className="date-badge">{i<2?'TODAY':'UPCOMING'}</span><button className="favorite" onClick={ev=>{ev.stopPropagation();toggle(e.id)}}><Heart size={18} fill={saved.includes(e.id)?'currentColor':'none'}/></button></div><div className="card-copy"><p className="category-label">{e.category}</p><h3>{e.title}</h3><p><MapPin size={14}/>{e.meta}</p></div></article>)}</div></section>
   <section className="benefits"><div><MapPin/><strong>LOCAL FOCUS</strong><span>South Bend, Mishawaka, Elkhart & Niles</span></div><div><CalendarDays/><strong>ALWAYS UPDATED</strong><span>Fresh listings from verified local sources</span></div><div><Heart/><strong>SAVE FAVORITES</strong><span>Keep track of ideas you want to try</span></div><div><Share2/><strong>SHARE & EXPLORE</strong><span>Find something fun and bring someone along</span></div></section>
  </main>
 </div>
}