import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Compass, Heart, MapPin, Search, Sparkles, UserRound, Utensils, Music2, Trophy, Trees, Palette, Users, MoonStar } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

type CardItem={id:string;label:string;title:string;meta:string;category:string;tags:string[];free?:boolean;tone:string;imageUrl?:string|null;sourceUrl?:string|null};
const supabase=createClient('https://vtvxzdvsnjhdkgtgzdxw.supabase.co','sb_publishable_aFbMLAqQB9NGtqcEL3xf4w_tj-o5M3p');
const filters=['Free','Family','Food','Music','Sports','Date Night','Arts','Outdoors'];
const icons:any={Family:Users,Food:Utensils,Music:Music2,Sports:Trophy,'Date Night':MoonStar,Arts:Palette,Outdoors:Trees};
const timeFilters=['NOW','TODAY','WEEKEND'];
const tone=(c:string)=>{const x=c.toLowerCase();return x.includes('music')?'music':x.includes('sport')?'sports':x.includes('food')?'food':x.includes('outdoor')?'outdoors':x.includes('family')?'family':x.includes('art')?'date':'festival'};
const eventMeta=(e:any)=>{const d=new Date(e.start_time);return `${d.toLocaleDateString([], {month:'short',day:'numeric'})} · ${d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}${e.venue_name?` · ${e.venue_name}`:''}`};

export default function App(){
 const[time,setTime]=useState('TODAY');const[filter,setFilter]=useState<string|null>(null);const[saved,setSaved]=useState<string[]>([]);const[items,setItems]=useState<CardItem[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{setLoading(true);const now=new Date().toISOString();const[{data:events},{data:places}]=await Promise.all([supabase.from('events').select('id,title,category,tags,start_time,venue_name,is_free,image_url,source_url,family_friendly').eq('status','active').gte('start_time',now).order('start_time').limit(80),supabase.from('places').select('id,name,category,tags,city,image_url,website_url').eq('active',true).limit(80)]);const ev=(events||[]).map((e:any):CardItem=>({id:`e-${e.id}`,label:e.is_free?'Free Pick':'Verified Event',title:e.title,meta:eventMeta(e),category:e.category||'Community',tags:[...(e.tags||[]),...(e.family_friendly?['Family']:[])],free:e.is_free,tone:tone(e.category||''),imageUrl:e.image_url,sourceUrl:e.source_url}));const food=(places||[]).filter((p:any)=>String(p.category||'').toLowerCase().includes('food')||(p.tags||[]).some((t:string)=>/food|restaurant|coffee|dessert/i.test(t))).map((p:any):CardItem=>({id:`p-${p.id}`,label:'Local Food',title:p.name,meta:`${p.city||'Michiana'} · Local place`,category:'Food',tags:['Food',...(p.tags||[]).slice(0,1)],tone:'food',imageUrl:p.image_url,sourceUrl:p.website_url}));setItems([...ev,...food]);setLoading(false)})()},[]);
 const visible=useMemo(()=>items.filter(i=>{if(filter==='Food')return i.category==='Food'||i.tags.includes('Food');if(filter==='Free')return i.free;if(filter==='Date Night')return i.tags.includes('Date Night')||['Food','Music','Arts'].includes(i.category);if(filter&&!(i.category===filter||i.tags.includes(filter)))return false;if(i.id.startsWith('p-'))return filter==='Food'||filter==='Date Night';return true}),[items,filter]);
 const toggle=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <div className="app-shell"><header className="brand-header"><img className="brand-logo" src="/im-bored-logo.webp" alt="I'm Bored, Find Something Fun to Do"/><button className="icon-button" aria-label="Profile"><UserRound size={20}/></button></header><main>
 <section className="hero-card"><div className="hero-glow"/><div className="hero-copy"><p className="hero-kicker">LIVE MICHIANA DISCOVERY</p><h2>Find something fun to do.</h2><p>Real events, food, sports, family activities and hidden gems within about 30 miles of 46637.</p></div><div className="hero-actions"><button className="primary-cta"><Sparkles size={19}/> SURPRISE ME</button><button className="location-pill"><MapPin size={16}/>46637 · 30 mi</button></div></section>
 <section className="control-section"><div className="segmented">{timeFilters.map(x=><button key={x} className={time===x?'active':''} onClick={()=>setTime(x)}>{x}</button>)}</div></section>
 <section className="control-section"><div className="section-heading"><div><p className="eyebrow">PICK A VIBE</p><h3>What sounds good?</h3></div>{filter&&<button className="text-button" onClick={()=>setFilter(null)}>Clear</button>}</div><div className="chips">{filters.map(x=>{const I=icons[x];return <button key={x} className={filter===x?'chip selected':'chip'} onClick={()=>setFilter(filter===x?null:x)}>{I&&<I size={15}/>} {x}</button>})}</div></section>
 <section className="results-section"><div className="section-heading"><div><p className="eyebrow">{filter?`${filter.toUpperCase()} · ${time}`:`LIVE PICKS · ${time}`}</p><h3>{loading?'Loading verified ideas…':visible.length?`${visible.length} verified ideas`:'No verified matches yet'}</h3></div><Search size={19}/></div><div className="event-grid">{visible.map((e,i)=><article className="event-card" key={e.id} onClick={()=>e.sourceUrl&&window.open(e.sourceUrl,'_blank','noopener,noreferrer')}><div className={`event-image ${e.tone}`} style={e.imageUrl?{backgroundImage:`linear-gradient(25deg,rgba(0,0,0,.45),rgba(0,0,0,.05)),url(${e.imageUrl})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><span>{e.category}</span><strong>{i===0?'TOP PICK':'VERIFIED'}</strong></div><div className="event-body"><div className="event-topline"><span className="badge">{e.label}</span><button className="save-button" onClick={ev=>{ev.stopPropagation();toggle(e.id)}} aria-label="Save"><Heart size={18} fill={saved.includes(e.id)?'currentColor':'none'}/></button></div><h4>{e.title}</h4><p>{e.meta}</p><div className="card-tags">{e.tags.slice(0,2).map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
 </main><nav className="bottom-nav"><button className="nav-active"><Compass size={20}/><span>Discover</span></button><button><MapPin size={20}/><span>Explore</span></button><button><Heart size={20}/><span>Saved{saved.length?` ${saved.length}`:''}</span></button><button><CalendarDays size={20}/><span>Plans</span></button></nav></div>
}